[project]
name = "uc-intg-broadlink"
version = "1.0.0"
description = "Broadlink integration for Unfolded Circle Remotes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyee>=9.0.0",
    "ucapi==0.4.0",
    "broadlink==0.19.0",
    "ucapi-framework==1.2.2",
]
